name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies with pip
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-cov vcrpy faker factory-boy black ruff mypy types-redis
    
    - name: Run linting
      run: |
        ruff check src/ || true
        flake8 src/ || true
    
    - name: Run type checking
      run: mypy src/ || true
    
    - name: Run tests
      run: pytest tests/ -v --cov=src --cov-report=xml || true
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: docker build -t amazon-review-scraper:test .
    
    - name: Start Redis container
      run: |
        docker run -d --name redis-test -p 6379:6379 redis:7-alpine
        sleep 5
    
    - name: Run Docker container
      run: |
        docker run -d --name test-container \
          --link redis-test:redis \
          -p 8080:8080 \
          -e REDIS_URL=redis://redis:6379/0 \
          amazon-review-scraper:test
        sleep 10
    
    - name: Test health endpoint
      run: |
        curl -f http://localhost:8080/health || exit 1
    
    - name: Stop containers
      run: |
        docker stop test-container || true
        docker stop redis-test || true